<a href="https://colab.research.google.com/github/sujata533/sujata533/blob/main/Smoking_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# data manipulation
import pandas as pd

# data transformation
import numpy as np

# visualizations
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load the data

smoke = pd.read_csv('/content/smoking_data.csv')
smoke.head(3)

,Country,Year,Total Smokers (Millions),Smoking Prevalence (%),Male Smokers (%),Female Smokers (%),Cigarette Consumption (Billion Units),Top Cigarette Brand in Country,Brand Market Share (%),Smoking-Related Deaths,Tobacco Tax Rate (%),Smoking Ban Policy
0,South Africa,2010,279.6,21.5,13.3,8.2,2415.7,Peter Stuyvesant,21.3,461574,32.9,Partial
1,South Africa,2022,41.8,10.2,7.5,2.7,97.0,Peter Stuyvesant,46.6,57945,42.9,Comprehensive
2,South Africa,2017,262.0,30.7,22.1,8.6,161.5,Peter Stuyvesant,58.5,407834,51.4,Partial

In [3]:
smoke.shape

(150, 12)

In [4]:
smoke.columns.to_list()

['Country',
 'Year',
 'Total Smokers (Millions)',
 'Smoking Prevalence (%)',
 'Male Smokers (%)',
 'Female Smokers (%)',
 'Cigarette Consumption (Billion Units)',
 'Top Cigarette Brand in Country',
 'Brand Market Share (%)',
 'Smoking-Related Deaths',
 'Tobacco Tax Rate (%)',
 'Smoking Ban Policy']

In [5]:
smoke.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Country                                150 non-null    object
 1   Year                                   150 non-null    int64
 2   Total Smokers (Millions)               150 non-null    float64
 3   Smoking Prevalence (%)                 150 non-null    float64
 4   Male Smokers (%)                       150 non-null    float64
 5   Female Smokers (%)                     150 non-null    float64
 6   Cigarette Consumption (Billion Units)  150 non-null    float64
 7   Top Cigarette Brand in Country         150 non-null    object
 8   Brand Market Share (%)                 150 non-null    float64
 9   Smoking-Related Deaths                 150 non-null    int64
 10  Tobacco Tax Rate (%)                   150 non-null    float64
 11  Smoking Ban Policy                     102 non-null    object
dtypes: float64(7), int64(2), object(3)
memory usage: 14.2+ KB

In [6]:
#  statistical summary
smoke.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Country,150,20,South Africa,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,150.0,NaN,NaN,NaN,2018.066667,4.38984,2010.0,2014.0,2018.0,2022.0,2024.0
Total Smokers (Millions),150.0,NaN,NaN,NaN,170.466,100.806168,2.7,86.225,165.0,256.625,344.1
Smoking Prevalence (%),150.0,NaN,NaN,NaN,23.387333,9.697494,5.9,15.6,22.8,31.0,39.9
Male Smokers (%),150.0,NaN,NaN,NaN,17.719333,8.2048,3.8,11.725,16.9,23.725,34.2
Female Smokers (%),150.0,NaN,NaN,NaN,5.668,2.844335,0.9,3.4,5.0,7.5,15.2
Cigarette Consumption (Billion Units),150.0,NaN,NaN,NaN,927.815333,773.890041,4.3,290.85,753.05,1358.475,3238.6
Top Cigarette Brand in Country,150,17,Marlboro,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Brand Market Share (%),150.0,NaN,NaN,NaN,33.956667,14.643969,10.1,20.55,33.3,45.775,59.9
Smoking-Related Deaths,150.0,NaN,NaN,NaN,224419.926667,160056.39574,4452.0,84614.75,190765.5,349719.0,606058.0
Tobacco Tax Rate (%),150.0,NaN,NaN,NaN,57.835333,17.996011,30.1,42.35,55.25,75.0,89.8
Smoking Ban Policy,102,2,Partial,65,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.1)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.1.4)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.4/400.4 kB 9.5 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 22.5 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 69.6 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 47.1 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 11.0 MB/s eta 0:00:00
Downloading puremagic-2.0.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.9/65.9 kB 6.4 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.0.0 visions-0.8.1 ydata-profiling-4.18.1

In [8]:
from ydata_profiling import ProfileReport

profile = ProfileReport(smoke, title='Smoke Trends Summary', explorative=True)

profile.to_file('smoke_summary.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]
100%|██████████| 12/12 [00:00<00:00, 85.24it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]